apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: change-image-tag
spec:
  templates:
  - name: change
    inputs:
      parameters:
      - name: repo_owner
      - name: repo_name
      - name: image_owner
      - name: image_name
      - name: tag
    script:
      image: bitnami/git
      command: [sh]
      source: |
        git clone https://$(cat /.github/token)@github.com/{{inputs.parameters.repo_owner}}/{{inputs.parameters.repo_name}}
        sleep 2
        cd {{inputs.parameters.repo_name}}/helm
        echo BEFORE:
        cat values.yaml
        echo AFTER:
        sed -i -E 's/tag.*/tag: {{inputs.parameters.tag}}/' values.yaml
        cat values.yaml
        git config user.name $(cat /.github/user)
        git config user.email $(cat /.github/email)
        git commit -a -m "Upgraded image {{inputs.parameters.image_name}} with the tag {{inputs.parameters.tag}}"
        git push
      volumeMounts:
      - name: github-access
        mountPath: /.github/
